# Generated by Django 5.2.5 on 2025-09-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='portrait',
            field=models.ImageField(blank=True, null=True, upload_to='portraits/'),
        ),
        migrations.AddField(
            model_name='book',
            name='preview',
            field=models.FileField(blank=True, null=True, upload_to='previews/'),
        ),
    ]
